### ISSUE TITLE
Update for last martor release

### ISSUE THREAD

**Issue by askurashev** [Yawan-1/StackOverFlow--Clone#19]

**Comment by Yawan-1** [comment]
@askurashev What?

**Comment by controldevil007** [comment]
> @askurashev What?
i see an app named "martor" mentioned in the installed_apps in main/settings.py  but their is no app named martor in file structure of the project.

**Comment by Yawan-1** [comment]
@controldevil007 `Martor` is third party package not a project's app mentioned in [requirements.txt](https://github.com/Yawan-1/StackOverFlow--Clone/blob/master/requirements.txt#L31).

And I'd suggest you to download requirements.txt packages using `pip install -r requirements.txt` and not separately because packages may have released new versions and new version of package may not work with the Project and can create issues.
